# Generated by Django 3.1.6 on 2021-02-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amonthatatime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.IntegerField(default='0000'),
        ),
        migrations.AlterField(
            model_name='post',
            name='month',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
