# Generated by Django 3.1.6 on 2021-02-05 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amonthatatime', '0002_auto_20210201_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gram',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='medley',
            field=models.TextField(default=0),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='amonthatatime.post')),
            ],
        ),
    ]
