# Generated by Django 3.1.6 on 2021-02-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amonthatatime', '0003_auto_20210205_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='images',
            new_name='grams',
        ),
        migrations.RemoveField(
            model_name='post',
            name='gram',
        ),
    ]
