# Generated by Django 3.1.6 on 2021-02-06 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amonthatatime', '0008_postimage_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='status',
            new_name='columns',
        ),
    ]
