# Generated by Django 3.1.6 on 2021-02-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amonthatatime', '0012_auto_20210207_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='grams_string',
            field=models.TextField(default='na'),
        ),
        migrations.AlterField(
            model_name='post',
            name='medley',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='month',
            field=models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.IntegerField(default='2021'),
        ),
    ]
