# Generated by Django 3.1.6 on 2021-02-20 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amonthatatime', '0017_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='grams',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='grams_string',
        ),
    ]
