# Generated by Django 3.1.6 on 2021-02-20 02:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amonthatatime', '0018_auto_20210220_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='grams',
            field=cloudinary.models.CloudinaryField(default='null', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
