# Generated by Django 3.1.6 on 2021-02-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amonthatatime', '0020_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='urls',
            field=models.TextField(default='na'),
        ),
    ]
