# Generated by Django 3.1.6 on 2021-02-20 15:31

import amonthatatime.pythonsupport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amonthatatime', '0021_test_urls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='postimage',
            name='urls',
            field=models.TextField(default='na'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='grams',
            field=models.FileField(upload_to=amonthatatime.pythonsupport.models.newletter_gram_path),
        ),
    ]
