# Generated by Django 3.1.6 on 2021-02-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amonthatatime', '0022_auto_20210220_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(choices=[('general', 'general')], max_length=20)),
                ('photo', models.FileField(upload_to='amonthatatime/images/<django.db.models.fields.CharField>')),
                ('urls', models.TextField(default='na')),
            ],
        ),
    ]
