# Generated by Django 3.1.6 on 2021-02-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amonthatatime', '0024_auto_20210221_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='month_number',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='month',
            field=models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=20),
        ),
    ]
