# Generated by Django 3.1.6 on 2021-02-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amonthatatime', '0025_auto_20210221_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='na', max_length=40),
        ),
    ]
