# Generated by Django 3.1.6 on 2021-02-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amonthatatime', '0007_auto_20210205_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='status',
            field=models.IntegerField(choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)], default=4),
        ),
    ]
