# Generated by Django 3.1.6 on 2021-02-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amonthatatime', '0011_auto_20210207_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='month',
            field=models.CharField(choices=[('january', 'January'), ('February', 'february'), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=20),
        ),
    ]
