# Generated by Django 3.1.6 on 2021-04-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210408_1820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Idea',
        ),
    ]
