# Generated by Django 3.1.6 on 2021-04-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210408_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
