# Generated by Django 3.1.6 on 2021-02-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amonthatatime', '0004_auto_20210205_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='caption',
            field=models.TextField(default=0),
        ),
    ]
