# Generated by Django 3.1.6 on 2021-02-05 21:44

import amonthatatime.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amonthatatime', '0005_postimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='grams',
            field=models.FileField(upload_to=amonthatatime.models.newletter_gram_path),
        ),
    ]
