# Generated by Django 3.1.6 on 2021-02-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amonthatatime', '0006_auto_20210205_2144'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('year', 'month')},
        ),
    ]
