# Generated by Django 3.1.6 on 2021-02-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amonthatatime', '0009_auto_20210206_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='columns',
        ),
        migrations.AddField(
            model_name='post',
            name='photo_columns',
            field=models.IntegerField(choices=[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)], default=4),
        ),
    ]
