# Generated by Django 3.1.6 on 2021-02-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amonthatatime', '0010_auto_20210206_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='month',
            field=models.TextField(choices=[('january', 'January'), ('February', 'february'), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_columns',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=4),
        ),
    ]
